apiVersion: apps/v1
kind: Deployment
metadata:
  name: predictor
  labels:
    app: predictor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: predictor
  template:
    metadata:
      labels:
        app: predictor
    spec:
      containers:
      - name: predictor
        image: ashprince/predictor-stage:latest
        ports:
        - containerPort: 5000
        env:
        - name: FLASK_ENV
          value: "production"
---
apiVersion: v1
kind: Service
metadata:
  name: predictor
spec:
  type: NodePort
  selector:
    app: predictor
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 30000