apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: phpmyadmin
  name: phpmyadmin
spec:
  ports:
    - name: "8085"
      port: 8085
      targetPort: 80
  selector:
    io.kompose.service: phpmyadmin
